services:
  mongo:
    image: mongo:7.0
    container_name: reservation-mongo
    restart: always
    command: ["--replSet", "rs0", "--bind_ip_all"]
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: mongosh --port 27017 --eval 'rs.status().ok || rs.initiate()' || exit 1
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 3s

volumes:
  mongo_data:
